version: '3'

services:
  database_os:
    image: mysql:5.7
    volumes:
      - db_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: shubham
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb



  ghost_os:
    image: ghost:1-alpine
    restart: always
    depends_on:
      - database_os
    ports:
      - 8082:2368
    environment:
      database_client: mysql
      database_connection: database_os 
      database_connection_user: shubham
      database_connection_password: mydb
      database_connection_database: mydb
    volumes:
      - gh_storage_new:/var/lib/ghost

volumes:
  gh_storage_new:
  db_storage_new:










            
